backend:
   name: github # github id로 로그인하려고 github이라고 해두었음.
   repo:  Sunghyun01/Gatsby-blog
   branch: master
media_folder: static/img
public_folder: /img
collections:
   - name: 'test'
     label: 'test'
     folder: 'content/blog/test'
     create: true
     slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
     editor:
       preview: true
     fields:
       - { label: 'Title', name: 'title', widget: 'string' }
       - { label: 'category', name: 'category', widget: 'hidden', default: 'test'}
       - { label: 'Draft', name: 'draft', widget: 'hidden', default: false}
       - { label: 'Publish Date', name: 'date', widget: 'datetime' }
       - { label: 'Description', name: 'description', widget: 'string' }
       - { label: 'Body', name: 'body', widget: 'markdown' }
   - name: 'default'
     label: 'default'
     folder: 'content/blog/default'
     create: true
     slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
     editor:
       preview: true
     fields:
       - { label: 'Title', name: 'title', widget: 'string' }
       - { label: 'category', name: 'category', widget: 'hidden', default: 'default'}
       - { label: 'Draft', name: 'draft', widget: 'hidden', default: false}
       - { label: 'Publish Date', name: 'date', widget: 'datetime' }
       - { label: 'Description', name: 'description', widget: 'string' }
       - { label: 'Body', name: 'body', widget: 'markdown' }